# Generated by Django 6.0.6

from django.db import migrations, models
import django.db.models.deletion


def grandfather_existing_accounts(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(plan='free', subscription_status='none').update(
        plan='solo',
        subscription_status='active',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_interval',
            field=models.CharField(
                blank=True,
                choices=[('month', 'Monthly'), ('year', 'Annual')],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation_owner',
            field=models.ForeignKey(
                blank=True,
                help_text='The paid Organisation account that provides access to this member.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='organisation_members',
                to='accounts.user',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(
                choices=[('free', 'Free'), ('solo', 'Solo'), ('organisation', 'Organisation')],
                default='free',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(
                choices=[
                    ('none', 'No subscription'),
                    ('active', 'Active'),
                    ('trialing', 'Trialing'),
                    ('past_due', 'Payment past due'),
                    ('unpaid', 'Payment failed'),
                    ('incomplete', 'Payment incomplete'),
                    ('incomplete_expired', 'Payment incomplete and expired'),
                    ('canceled', 'Canceled'),
                ],
                default='none',
                max_length=30,
            ),
        ),
        migrations.RunPython(
            grandfather_existing_accounts,
            reverse_code=migrations.RunPython.noop,
        ),
    ]