# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_event_created',
            field=models.BigIntegerField(default=0),
        ),
    ]