# Generated by Django 6.0.6 on 2026-08-30 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_stripe_event_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationDataTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_policy', models.CharField(choices=[('member', 'Keep with member'), ('organisation', 'Retain in organisation account')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('transferred_solo_count', models.PositiveIntegerField(default=0)),
                ('transferred_session_count', models.PositiveIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_data_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_data_transfer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('owner', models.F('member')), _negated=True), name='organisation_transfer_owner_not_member'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('member',), name='one_pending_organisation_transfer_per_member')],
            },
        ),
        migrations.CreateModel(
            name='OrganisationMemberDataPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(choices=[('member', 'Keep with member'), ('organisation', 'Retain in organisation account')], default='member', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_data_policy', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_data_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('owner', models.F('member')), _negated=True), name='organisation_policy_owner_not_member')],
            },
        ),
    ]
