# Generated by Django 6.0.4 on 2026-04-25 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_slug', models.CharField(max_length=100)),
                ('tool_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='toolinstance',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Set when this instance is part of a collaborative session.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='archive.toolsession'),
        ),
        migrations.AddConstraint(
            model_name='toolinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('session', 'user'), name='unique_session_user_instance'),
        ),
    ]
