# Generated by Django 6.0.4 on 2026-04-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_toolsession_toolinstance_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsession',
            name='md_file',
            field=models.FileField(blank=True, null=True, upload_to='archives/md/'),
        ),
        migrations.AddField(
            model_name='toolsession',
            name='rtf_file',
            field=models.FileField(blank=True, null=True, upload_to='archives/rtf/'),
        ),
    ]
