# Generated by Django 6.0.4 on 2026-05-16 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_feature_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='toolinstance',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Display name entered by a guest participant (user is null).', max_length=100),
        ),
        migrations.AddField(
            model_name='toolsession',
            name='guest_token',
            field=models.UUIDField(default=uuid.uuid4, help_text='Token embedded in the guest QR code URL. Anyone with this token can join as an unauthenticated guest.'),
        ),
        migrations.AlterField(
            model_name='toolinstance',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for unauthenticated guest participants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
