# Generated by Django 6.0.6 on 2026-08-30 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_toolsession_verbal_breakout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='toolinstance',
            name='data_owner',
            field=models.ForeignKey(blank=True, help_text='Retention owner; creator attribution is kept separately.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tool_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolsession',
            name='data_owner',
            field=models.ForeignKey(blank=True, help_text='Retention owner; host attribution is kept separately.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('submit', 'Tool Submission'), ('download', 'File Download'), ('access_denied', 'Unauthorized Access Attempt'), ('organisation_transfer_requested', 'Organisation Data Transfer Requested'), ('organisation_transfer_accepted', 'Organisation Data Transfer Accepted'), ('organisation_transfer_declined', 'Organisation Data Transfer Declined')], max_length=40),
        ),
    ]
