# Generated by Django 6.0.8

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_slug', models.SlugField(max_length=80)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('completed_at',),
                'constraints': [
                    models.UniqueConstraint(fields=('user', 'lesson_slug'), name='unique_academy_lesson_progress'),
                ],
            },
        ),
    ]